[package]
name = "msp432_blink"
version = "0.1.0"
authors = ["Raz Aloni <raz-@outlook.com>"]
edition = "2018"

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
debug = true

[dependencies]
msp432_razcal = {git = "https://github.com/raz-a/msp432_razcal"}